from fastapi.testclient import TestClient

from app.main import app


client = TestClient(app)


def test_root_endpoint():
    response = client.get("/")

    assert response.status_code == 200
    assert response.json()["application"] == "ScaleProof QA"


def test_health_endpoint():
    response = client.get("/health")
    body = response.json()

    assert response.status_code == 200
    assert body["status"] == "healthy"
    assert body["service"] == "scaleproof-test-api"
    assert "timestamp" in body


def test_products_endpoint():
    response = client.get("/api/products")
    body = response.json()

    assert response.status_code == 200
    assert body["total"] == 3
    assert len(body["products"]) == 3
    assert all(product["stock"] >= 0 for product in body["products"])

def test_create_order_successfully():
    order_payload = {
        "customer_id": 101,
        "items": [
            {"product_id": 1, "quantity": 2},
            {"product_id": 3, "quantity": 1},
        ],
    }

    response = client.post("/api/orders", json=order_payload)
    body = response.json()

    assert response.status_code == 201
    assert body["order_id"].startswith("ORD-")
    assert body["customer_id"] == 101
    assert body["status"] == "confirmed"
    assert body["total_items"] == 3


def test_reject_order_with_invalid_quantity():
    invalid_order = {
        "customer_id": 101,
        "items": [
            {"product_id": 1, "quantity": 0},
        ],
    }

    response = client.post("/api/orders", json=invalid_order)

    assert response.status_code == 422

def test_metrics_endpoint():
    response = client.get("/metrics")

    assert response.status_code == 200
    assert "scaleproof_http_requests_total" in response.text
    assert "scaleproof_http_request_duration_seconds" in response.text
    assert "scaleproof_cpu_usage_percent" in response.text
    assert "scaleproof_memory_usage_percent" in response.text


def test_metrics_record_health_requests():
    client.get("/health")
    response = client.get("/metrics")

    assert 'endpoint="/health"' in response.text
    assert 'method="GET"' in response.text
    assert 'status_code="200"' in response.text

def test_reliability_endpoint_with_controlled_delay():
    response = client.get(
        "/api/reliability/simulate",
        params={"delay_ms": 100, "force_failure": False},
    )
    body = response.json()

    assert response.status_code == 200
    assert body["status"] == "available"
    assert body["simulated_delay_ms"] == 100
    assert body["failure_injected"] is False


def test_reliability_endpoint_with_forced_failure():
    response = client.get(
        "/api/reliability/simulate",
        params={"delay_ms": 0, "force_failure": True},
    )

    assert response.status_code == 503
    assert response.json()["detail"] == (
        "Controlled service failure generated by ScaleProof QA."
    )


def test_reliability_endpoint_rejects_excessive_delay():
    response = client.get(
        "/api/reliability/simulate",
        params={"delay_ms": 2001, "force_failure": False},
    )

    assert response.status_code == 422