from datetime import datetime, timezone
from fastapi import FastAPI, HTTPException, Query
from uuid import uuid4
from pydantic import BaseModel, Field
from app.metrics import collect_request_metrics, prometheus_metrics_response
import time

class OrderItem(BaseModel):
    product_id: int = Field(gt=0)
    quantity: int = Field(gt=0, le=10)


class OrderRequest(BaseModel):
    customer_id: int = Field(gt=0)
    items: list[OrderItem]

app = FastAPI(
    title="ScaleProof QA Test API",
    description="A realistic API used for performance, scalability, and reliability testing.",
    version="1.0.0",
)

app.middleware("http")(collect_request_metrics)

@app.get("/")
def read_root():
    return {
        "application": "ScaleProof QA",
        "message": "Enterprise Performance Testing & Reliability Platform",
    }


@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "scaleproof-test-api",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


@app.get("/api/products")
def get_products():
    return {
        "products": [
            {"id": 1, "name": "Laptop", "price": 999.99, "stock": 25},
            {"id": 2, "name": "Headphones", "price": 149.99, "stock": 80},
            {"id": 3, "name": "Keyboard", "price": 79.99, "stock": 45},
        ],
        "total": 3,
    }

@app.post("/api/orders", status_code=201)
def create_order(order: OrderRequest):
    total_quantity = sum(item.quantity for item in order.items)

    return {
        "order_id": f"ORD-{uuid4().hex[:8].upper()}",
        "customer_id": order.customer_id,
        "status": "confirmed",
        "total_items": total_quantity,
    }

@app.get("/metrics", tags=["Observability"])
def get_metrics():
    return prometheus_metrics_response()

@app.get("/api/reliability/simulate", tags=["Reliability Testing"])
def simulate_reliability_condition(
    delay_ms: int = Query(default=0, ge=0, le=2000),
    force_failure: bool = False,
):
    if delay_ms:
        time.sleep(delay_ms / 1000)

    if force_failure:
        raise HTTPException(
            status_code=503,
            detail="Controlled service failure generated by ScaleProof QA.",
        )

    return {
        "status": "available",
        "simulated_delay_ms": delay_ms,
        "failure_injected": False,
    }