from locust import HttpUser, between, task

from performance_tests import evaluator as _evaluator


class ReliabilityTestUser(HttpUser):
    host = "http://127.0.0.1:8000"
    wait_time = between(1, 2)

    @task(3)
    def verify_service_availability(self):
        with self.client.get(
            "/health",
            name="GET /health [availability]",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(
                    f"Availability check returned status {response.status_code}"
                )
            elif response.json().get("status") != "healthy":
                response.failure("Service reported an unhealthy state")
            else:
                response.success()

    @task(2)
    def verify_degraded_response(self):
        with self.client.get(
            "/api/reliability/simulate",
            params={"delay_ms": 250, "force_failure": False},
            name="GET /reliability [250ms delay]",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(
                    f"Degraded request returned status {response.status_code}"
                )
            elif response.json().get("simulated_delay_ms") != 250:
                response.failure("Expected latency simulation was not applied")
            else:
                response.success()

    @task(1)
    def verify_controlled_failure_contract(self):
        with self.client.get(
            "/api/reliability/simulate",
            params={"delay_ms": 0, "force_failure": True},
            name="GET /reliability [expected 503]",
            catch_response=True,
        ) as response:
            expected_message = (
                "Controlled service failure generated by ScaleProof QA."
            )

            if response.status_code != 503:
                response.failure(
                    f"Expected status 503 but received {response.status_code}"
                )
            elif response.json().get("detail") != expected_message:
                response.failure("Controlled failure message was incorrect")
            else:
                response.success()